# Generated by Django 5.2.3 on 2025-08-01 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('capacidad', models.PositiveIntegerField()),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('pasajeros', 'Pasajeros'), ('carga', 'Carga'), ('mixto', 'Mixto')], default='pasajeros', max_length=20)),
                ('autonomia_km', models.PositiveIntegerField(help_text='Autonomía en kilómetros')),
                ('fecha_fabricacion', models.DateField()),
                ('en_mantenimiento', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
