# Generated by Django 5.2.3 on 2025-07-27 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_genero_options_alter_localidad_options_and_more'),
        ('core', '0002_estado_tipovuelo'),
    ]

    operations = [
    ]
