# Generated by Django 5.2.3 on 2025-07-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_avion', models.CharField(max_length=20, unique=True)),
                ('modelo', models.CharField(max_length=50)),
                ('filas', models.PositiveIntegerField()),
                ('columnas', models.PositiveIntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('km_recorridos', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
