# Generated by Django 5.2.3 on 2025-07-18 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_avion', models.CharField(max_length=20, unique=True)),
                ('modelo', models.CharField(max_length=50)),
                ('filas', models.PositiveIntegerField()),
                ('columnas', models.PositiveIntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('km_recorridos', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.PositiveIntegerField()),
                ('columna', models.CharField(max_length=2)),
                ('estado', models.CharField(choices=[('libre', 'Libre'), ('reservado', 'Reservado'), ('ocupado', 'Ocupado')], default='libre', max_length=10)),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='aviones.avion')),
            ],
        ),
    ]
