# Generated by Django 5.2.3 on 2025-07-11 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.PositiveIntegerField()),
                ('columna', models.CharField(max_length=2)),
                ('estado', models.CharField(choices=[('libre', 'Libre'), ('reservado', 'Reservado'), ('ocupado', 'Ocupado')], default='libre', max_length=10)),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='aviones.avion')),
            ],
        ),
    ]
