# Generated by Django 5.2.3 on 2025-07-24 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviones', '0002_asiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asiento',
            options={'ordering': ['avion', 'fila', 'columna'], 'verbose_name': 'Asiento', 'verbose_name_plural': 'Asientos'},
        ),
        migrations.AlterModelOptions(
            name='avion',
            options={'ordering': ['num_avion'], 'verbose_name': 'Avión', 'verbose_name_plural': 'Aviones'},
        ),
        migrations.AlterField(
            model_name='asiento',
            name='avion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='aviones.avion', verbose_name='Avión'),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='columna',
            field=models.CharField(max_length=2, verbose_name='Columna'),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='estado',
            field=models.CharField(choices=[('libre', 'Libre'), ('reservado', 'Reservado'), ('ocupado', 'Ocupado')], default='libre', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='fila',
            field=models.PositiveIntegerField(verbose_name='Fila'),
        ),
        migrations.AlterField(
            model_name='avion',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='avion',
            name='columnas',
            field=models.PositiveIntegerField(verbose_name='Columnas'),
        ),
        migrations.AlterField(
            model_name='avion',
            name='estado',
            field=models.CharField(help_text='Ej: operativo, mantenimiento', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='avion',
            name='filas',
            field=models.PositiveIntegerField(verbose_name='Filas'),
        ),
        migrations.AlterField(
            model_name='avion',
            name='km_recorridos',
            field=models.PositiveIntegerField(default=0, verbose_name='Kilómetros Recorridos'),
        ),
        migrations.AlterField(
            model_name='avion',
            name='modelo',
            field=models.CharField(max_length=50, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='avion',
            name='num_avion',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número de Avión'),
        ),
        migrations.AlterUniqueTogether(
            name='asiento',
            unique_together={('avion', 'fila', 'columna')},
        ),
    ]
