# Generated by Django 5.2.3 on 2025-08-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviones', '0002_alter_asiento_options_alter_avion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asiento',
            name='columna',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Columna'),
        ),
    ]
