# Generated by Django 5.2.3 on 2025-08-14 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviones', '0003_alter_asiento_columna'),
    ]

    operations = [
        migrations.AddField(
            model_name='asiento',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
