# Generated by Django 5.2.3 on 2025-08-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviones', '0004_asiento_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asiento',
            name='tipo',
            field=models.CharField(choices=[('E', 'Economy'), ('B', 'Business'), ('F', 'First')], default='E', max_length=1, verbose_name='Tipo'),
        ),
    ]
