# Generated by Django 5.2.3 on 2025-08-11 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aviones', '0003_alter_asiento_columna'),
        ('vuelos', '0002_vuelo_tiene_escalas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Reserva')),
                ('precio_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Total')),
                ('codigo_reserva', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Código de Reserva')),
                ('estado', models.CharField(choices=[('CRE', 'Creada'), ('CON', 'Confirmada'), ('CAN', 'Cancelada')], default='CRE', max_length=3, verbose_name='Estado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='Pasajero')),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='vuelos.vuelo', verbose_name='Vuelo')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha_reserva'],
            },
        ),
        migrations.CreateModel(
            name='ReservaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aviones.asiento', verbose_name='Asiento')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='reservas.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Detalle de Reserva',
                'verbose_name_plural': 'Detalles de Reservas',
                'unique_together': {('reserva', 'asiento')},
            },
        ),
    ]
