# Generated by Django 5.2.3 on 2025-07-23 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_estado_tipovuelo'),
        ('vuelos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('fila', models.IntegerField()),
                ('columna', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('estado_pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estado')),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_vuelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipovuelo')),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuelos.vuelo')),
            ],
        ),
    ]
