# Generated by Django 5.2.3 on 2025-08-12 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estado_pago',
            field=models.CharField(choices=[('RES', 'Reservado'), ('PEN', 'Pendiente de Pago'), ('PAG', 'Pagado')], default='RES', max_length=3, verbose_name='Estado de Pago'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_limite_pago',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Límite de Pago'),
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Código de Barras')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('tipo_boleto', models.CharField(choices=[('PAG', 'Boleto Pagado'), ('PEN', 'Boleto Pendiente de Pago')], max_length=3, verbose_name='Tipo de Boleto')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boleto', to='reservas.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boletos',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
