# Generated by Django 5.2.3 on 2025-07-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='estado_pedido',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='columna',
            field=models.CharField(max_length=2),
        ),
    ]
