# Generated by Django 5.2.3 on 2025-08-12 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_estado_pago_reserva_fecha_limite_pago_boleto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='creado_por_admin',
            field=models.BooleanField(default=False, verbose_name='Creado por Admin'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='es_prefabricada',
            field=models.BooleanField(default=False, help_text='Reserva creada por admin, disponible para usuarios', verbose_name='Es Prefabricada'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('CRE', 'Creada'), ('CON', 'Confirmada'), ('CAN', 'Cancelada'), ('DIS', 'Disponible')], default='CRE', max_length=3, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='pasajero',
            field=models.ForeignKey(blank=True, help_text='Si es null, es una reserva prefabricada disponible para usuarios', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='Pasajero'),
        ),
    ]
