# Generated by Django 5.2.3 on 2025-08-13 00:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_reserva_creado_por_admin_reserva_es_prefabricada_and_more'),
        ('vuelos', '0003_alter_tripulacionescala_rol_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boleto',
            options={'ordering': ['-fecha_emision'], 'verbose_name': 'Boleto', 'verbose_name_plural': 'Boletos'},
        ),
        migrations.AlterModelOptions(
            name='reservadetalle',
            options={'verbose_name': 'Detalle de Reserva', 'verbose_name_plural': 'Detalles de Reserva'},
        ),
        migrations.RemoveField(
            model_name='boleto',
            name='fecha_generacion',
        ),
        migrations.RemoveField(
            model_name='boleto',
            name='tipo_boleto',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='creado_por_admin',
        ),
        migrations.AddField(
            model_name='boleto',
            name='asiento_snapshot',
            field=models.TextField(blank=True, help_text='JSON con datos de asientos al momento de generar boleto', null=True, verbose_name='Snapshot de Asientos'),
        ),
        migrations.AddField(
            model_name='boleto',
            name='fecha_emision',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Emisión'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boleto',
            name='tipo',
            field=models.CharField(choices=[('PAG', 'Pagado'), ('PEN', 'Pendiente')], default=1, max_length=3, verbose_name='Tipo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boleto',
            name='vuelo_snapshot',
            field=models.TextField(blank=True, help_text='JSON con datos del vuelo al momento de generar boleto', null=True, verbose_name='Snapshot de Vuelo'),
        ),
        migrations.AddField(
            model_name='reservadetalle',
            name='escala_vuelo',
            field=models.ForeignKey(blank=True, help_text='Solo si el vuelo tiene escalas', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vuelos.escalavuelo', verbose_name='Escala de Vuelo'),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='codigo_barras',
            field=models.CharField(editable=False, max_length=128, unique=True, verbose_name='Código de Barras'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='es_prefabricada',
            field=models.BooleanField(default=False, help_text='Reserva creada por admin sin usuario asignado', verbose_name='Es Prefabricada'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado_pago',
            field=models.CharField(choices=[('RES', 'Reservado'), ('PEN', 'Pendiente'), ('PAG', 'Pagado')], default='RES', max_length=3, verbose_name='Estado de Pago'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='pasajero',
            field=models.ForeignKey(blank=True, help_text='Null para reservas prefabricadas del admin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='Pasajero'),
        ),
    ]
