# Generated by Django 5.2.3 on 2025-08-13 22:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviones', '0003_alter_asiento_columna'),
        ('reservas', '0004_alter_boleto_options_alter_reservadetalle_options_and_more'),
        ('vuelos', '0003_alter_tripulacionescala_rol_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoVuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_asiento', models.CharField(choices=[('ECO', 'Económico'), ('PRE', 'Premium'), ('EJE', 'Ejecutivo'), ('PRI', 'Primera Clase')], default='ECO', max_length=3, verbose_name='Tipo de Asiento')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('habilitado_para_reserva', models.BooleanField(default=True, verbose_name='Habilitado para Reserva')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_configuracion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Configuración')),
            ],
            options={
                'verbose_name': 'Asiento de Vuelo',
                'verbose_name_plural': 'Asientos de Vuelo',
                'ordering': ['vuelo', 'escala_vuelo__orden', 'asiento__fila', 'asiento__columna'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionVuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configurado', models.BooleanField(default=False, verbose_name='Configurado')),
                ('fecha_configuracion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Configuración')),
                ('total_asientos_configurados', models.PositiveIntegerField(default=0, verbose_name='Total Asientos Configurados')),
                ('asientos_habilitados', models.PositiveIntegerField(default=0, verbose_name='Asientos Habilitados')),
            ],
            options={
                'verbose_name': 'Configuración de Vuelo',
                'verbose_name_plural': 'Configuraciones de Vuelo',
            },
        ),
        migrations.RemoveField(
            model_name='boleto',
            name='asiento_snapshot',
        ),
        migrations.RemoveField(
            model_name='boleto',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='es_prefabricada',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='estado_pago',
        ),
        migrations.AddField(
            model_name='boleto',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='boleto',
            name='asientos_snapshot',
            field=models.TextField(default='Sin Datos', help_text='JSON con información de asientos al momento de emisión', verbose_name='Datos de Asientos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boleto',
            name='fecha_uso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Uso'),
        ),
        migrations.AddField(
            model_name='boleto',
            name='pasajero_snapshot',
            field=models.TextField(default='Sin Datos', help_text='JSON con información del pasajero al momento de emisión', verbose_name='Datos del Pasajero'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boleto',
            name='usado',
            field=models.BooleanField(default=False, verbose_name='Usado'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=50, verbose_name='Método de Pago'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='numero_tarjeta_enmascarado',
            field=models.CharField(blank=True, max_length=19, verbose_name='Número de Tarjeta (enmascarado)'),
        ),
        migrations.AddField(
            model_name='reservadetalle',
            name='fecha_asignacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Asignación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservadetalle',
            name='precio_pagado',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Precio al momento de la reserva', max_digits=10, verbose_name='Precio Pagado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boleto',
            name='codigo_barras',
            field=models.CharField(editable=False, max_length=16, unique=True, verbose_name='Código de Barras'),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='vuelo_snapshot',
            field=models.TextField(default=1, help_text='JSON con información del vuelo al momento de emisión', verbose_name='Datos del Vuelo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='codigo_reserva',
            field=models.CharField(editable=False, max_length=16, unique=True, verbose_name='Código de Reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('CRE', 'Creada'), ('RSP', 'Reservado Sin Pago'), ('CON', 'Confirmada y Pagada'), ('CAN', 'Cancelada'), ('EXP', 'Expirada')], default='CRE', max_length=3, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='pasajero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='Pasajero'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='boleto',
            index=models.Index(fields=['codigo_barras'], name='reservas_bo_codigo__069400_idx'),
        ),
        migrations.AddIndex(
            model_name='boleto',
            index=models.Index(fields=['reserva'], name='reservas_bo_reserva_f0cedd_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['codigo_reserva'], name='reservas_re_codigo__ecd4f2_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['pasajero', 'estado'], name='reservas_re_pasajer_d6685e_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['vuelo', 'estado'], name='reservas_re_vuelo_i_c0b1b6_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['fecha_limite_pago'], name='reservas_re_fecha_l_96890b_idx'),
        ),
        migrations.AddField(
            model_name='asientovuelo',
            name='asiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviones.asiento', verbose_name='Asiento'),
        ),
        migrations.AddField(
            model_name='asientovuelo',
            name='configurado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Configurado Por'),
        ),
        migrations.AddField(
            model_name='asientovuelo',
            name='escala_vuelo',
            field=models.ForeignKey(blank=True, help_text='Solo para vuelos con escalas', null=True, on_delete=django.db.models.deletion.CASCADE, to='vuelos.escalavuelo', verbose_name='Escala de Vuelo'),
        ),
        migrations.AddField(
            model_name='asientovuelo',
            name='vuelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos_configurados', to='vuelos.vuelo', verbose_name='Vuelo'),
        ),
        migrations.AlterUniqueTogether(
            name='reservadetalle',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reservadetalle',
            name='asiento_vuelo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='reservas.asientovuelo', verbose_name='Asiento de Vuelo'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='reservadetalle',
            unique_together={('reserva', 'asiento_vuelo')},
        ),
        migrations.AddField(
            model_name='configuracionvuelo',
            name='configurado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Configurado Por'),
        ),
        migrations.AddField(
            model_name='configuracionvuelo',
            name='vuelo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_reserva', to='vuelos.vuelo', verbose_name='Vuelo'),
        ),
        migrations.AlterUniqueTogether(
            name='asientovuelo',
            unique_together={('vuelo', 'asiento', 'escala_vuelo')},
        ),
        migrations.RemoveField(
            model_name='reservadetalle',
            name='asiento',
        ),
        migrations.RemoveField(
            model_name='reservadetalle',
            name='escala_vuelo',
        ),
        migrations.RemoveField(
            model_name='reservadetalle',
            name='precio',
        ),
    ]
