# Generated by Django 5.2.3 on 2025-07-25 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aviones', '0002_alter_asiento_options_alter_avion_options_and_more'),
        ('core', '0002_alter_genero_options_alter_localidad_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_estimados', models.PositiveIntegerField(verbose_name='Kilómetros Estimados')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escalas_destino', to='core.localidad', verbose_name='Destino')),
                ('origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escalas_origen', to='core.localidad', verbose_name='Origen')),
            ],
            options={
                'verbose_name': 'Escala',
                'verbose_name_plural': 'Escalas',
            },
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_vuelo', models.CharField(max_length=20, unique=True)),
                ('fecha_salida_estimada', models.DateTimeField()),
                ('fecha_llegada_estimada', models.DateTimeField()),
                ('km_totales', models.PositiveIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('avion_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aviones.avion')),
                ('cargado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('destino_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vuelos_destino', to='core.localidad')),
                ('origen_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vuelos_origen', to='core.localidad')),
            ],
            options={
                'verbose_name': 'Vuelo',
                'verbose_name_plural': 'Vuelos',
                'ordering': ['fecha_salida_estimada'],
            },
        ),
        migrations.CreateModel(
            name='EscalaVuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden')),
                ('fecha_salida', models.DateTimeField(verbose_name='Fecha de Salida')),
                ('fecha_llegada', models.DateTimeField(verbose_name='Fecha de Llegada')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviones.avion', verbose_name='Avión')),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas_vuelo', to='vuelos.escala', verbose_name='Escala')),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas_vuelo', to='vuelos.vuelo', verbose_name='Vuelo')),
            ],
            options={
                'verbose_name': 'Escala de Vuelo',
                'verbose_name_plural': 'Escalas de Vuelo',
                'ordering': ['vuelo', 'orden'],
                'unique_together': {('vuelo', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='TripulacionEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('piloto', 'Piloto'), ('copiloto', 'Copiloto'), ('asistente', 'Asistente de vuelo'), ('jefe_cabina', 'Jefe de Cabina')], max_length=20, verbose_name='Rol')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('escala_vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripulacion_escala', to='vuelos.escalavuelo', verbose_name='Escala de Vuelo')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.persona', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Tripulación de Escala',
                'verbose_name_plural': 'Tripulaciones de Escala',
                'unique_together': {('escala_vuelo', 'persona', 'rol')},
            },
        ),
        migrations.CreateModel(
            name='TripulacionVuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('piloto', 'Piloto'), ('copiloto', 'Copiloto'), ('asistente', 'Asistente de vuelo'), ('jefe_cabina', 'Jefe de Cabina')], max_length=20, verbose_name='Rol')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.persona', verbose_name='Persona')),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripulacion', to='vuelos.vuelo', verbose_name='Vuelo')),
            ],
            options={
                'verbose_name': 'Tripulación de Vuelo',
                'verbose_name_plural': 'Tripulaciones de Vuelo',
                'unique_together': {('vuelo', 'persona', 'rol')},
            },
        ),
    ]
