# Generated by Django 5.2.3 on 2025-07-07 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aviones', '0001_initial'),
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_llegada', models.DateTimeField()),
                ('km_estimados', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas_destino', to='core.localidad')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas_origen', to='core.localidad')),
            ],
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_vuelo', models.CharField(max_length=20, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviones.avion')),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuelos', to='vuelos.escala')),
            ],
        ),
        migrations.CreateModel(
            name='TripulacionVuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('piloto', 'Piloto'), ('copiloto', 'Copiloto'), ('asistente', 'Asistente de vuelo')], max_length=20)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.persona')),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripulacion', to='vuelos.vuelo')),
            ],
        ),
    ]
