# Generated by Django 5.2.3 on 2025-07-30 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelo',
            name='tiene_escalas',
            field=models.BooleanField(default=False, verbose_name='Tiene Escalas'),
        ),
    ]
