# Generated by Django 5.2.3 on 2025-07-14 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pais_alter_localidad_options_provincia_and_more'),
        ('vuelos', '0002_alter_escala_options_alter_tripulacionvuelo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripulacionescala',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.persona'),
        ),
    ]
