# Generated by Django 5.2.3 on 2025-08-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0002_vuelo_tiene_escalas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripulacionescala',
            name='rol',
            field=models.CharField(choices=[('piloto', 'Piloto'), ('copiloto', 'Copiloto'), ('asistente', 'Asistente de vuelo'), ('jefe_cabina', 'Jefe de Cabina'), ('azafata', 'Azafata'), ('ingeniero', 'Ingeniero de Vuelo')], max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='tripulacionvuelo',
            name='rol',
            field=models.CharField(choices=[('piloto', 'Piloto'), ('copiloto', 'Copiloto'), ('asistente', 'Asistente de vuelo'), ('jefe_cabina', 'Jefe de Cabina'), ('azafata', 'Azafata'), ('ingeniero', 'Ingeniero de Vuelo')], max_length=20, verbose_name='Rol'),
        ),
    ]
