# Generated by Django 5.2.3 on 2025-07-14 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0002_alter_escala_options_alter_tripulacionvuelo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escalavuelo',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='escalavuelo',
            name='km_estimados',
        ),
        migrations.RemoveField(
            model_name='escalavuelo',
            name='origen',
        ),
        migrations.AddField(
            model_name='escalavuelo',
            name='escala',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='escalas_vuelo', to='vuelos.escala'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='escala',
            name='fecha_llegada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='escala',
            name='fecha_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
