# Generated by Django 5.2.3 on 2025-07-14 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0003_remove_escalavuelo_destino_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escala',
            name='fecha_llegada',
        ),
        migrations.RemoveField(
            model_name='escala',
            name='fecha_salida',
        ),
    ]
