# Generated by Django 5.2.3 on 2025-07-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0004_remove_escala_fecha_llegada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelo',
            name='km_totales',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
