# Generated by Django 5.2.3 on 2025-07-24 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviones', '0003_alter_asiento_options_alter_avion_options_and_more'),
        ('core', '0003_alter_genero_options_alter_localidad_options_and_more'),
        ('vuelos', '0005_alter_vuelo_km_totales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='escala',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escalas_destino', to='core.localidad', verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='escala',
            name='km_estimados',
            field=models.PositiveIntegerField(verbose_name='Kilómetros Estimados'),
        ),
        migrations.AlterField(
            model_name='escala',
            name='origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escalas_origen', to='core.localidad', verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='escalavuelo',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='escalavuelo',
            name='avion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviones.avion', verbose_name='Avión'),
        ),
        migrations.AlterField(
            model_name='escalavuelo',
            name='escala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas_vuelo', to='vuelos.escala', verbose_name='Escala'),
        ),
        migrations.AlterField(
            model_name='escalavuelo',
            name='fecha_llegada',
            field=models.DateTimeField(verbose_name='Fecha de Llegada'),
        ),
        migrations.AlterField(
            model_name='escalavuelo',
            name='fecha_salida',
            field=models.DateTimeField(verbose_name='Fecha de Salida'),
        ),
        migrations.AlterField(
            model_name='escalavuelo',
            name='orden',
            field=models.PositiveIntegerField(default=1, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='escalavuelo',
            name='vuelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas_vuelo', to='vuelos.vuelo', verbose_name='Vuelo'),
        ),
        migrations.AlterField(
            model_name='tripulacionescala',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='tripulacionescala',
            name='escala_vuelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripulacion_escala', to='vuelos.escalavuelo', verbose_name='Escala de Vuelo'),
        ),
        migrations.AlterField(
            model_name='tripulacionescala',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.persona', verbose_name='Persona'),
        ),
        migrations.AlterField(
            model_name='tripulacionescala',
            name='rol',
            field=models.CharField(choices=[('piloto', 'Piloto'), ('copiloto', 'Copiloto'), ('asistente', 'Asistente de vuelo'), ('jefe_cabina', 'Jefe de Cabina')], max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='tripulacionvuelo',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='tripulacionvuelo',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.persona', verbose_name='Persona'),
        ),
        migrations.AlterField(
            model_name='tripulacionvuelo',
            name='rol',
            field=models.CharField(choices=[('piloto', 'Piloto'), ('copiloto', 'Copiloto'), ('asistente', 'Asistente de vuelo'), ('jefe_cabina', 'Jefe de Cabina')], max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='tripulacionvuelo',
            name='vuelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripulacion', to='vuelos.vuelo', verbose_name='Vuelo'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='avion_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aviones.avion', verbose_name='Avión Asignado'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='cargado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cargado Por'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='codigo_vuelo',
            field=models.CharField(max_length=20, unique=True, verbose_name='Código de Vuelo'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='destino_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vuelos_destino', to='core.localidad', verbose_name='Destino Principal'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='fecha_carga',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='fecha_llegada_estimada',
            field=models.DateTimeField(verbose_name='Fecha de Llegada Estimada'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='fecha_salida_estimada',
            field=models.DateTimeField(verbose_name='Fecha de Salida Estimada'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='km_totales',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilómetros Totales'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='origen_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vuelos_origen', to='core.localidad', verbose_name='Origen Principal'),
        ),
    ]
